name:                HasKonnect4
version:             0.1.0.0
github:              "NeoVier/HasKonnect4"
license:             BSD3
author:              "Henrique Buss"
maintainer:          "henrique.buss@hotmail.com"
copyright:           "2020 Henrique Buss"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/NeoVier/HasKonnect4#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- gloss

library:
  source-dirs: src

executables:
  HasKonnect4-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HasKonnect4

tests:
  HasKonnect4-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HasKonnect4
